name: connect-publish
on:
  push:
    branches: [main, master]

jobs:
  connect-publish:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: http://ec2-3-144-123-91.us-east-2.compute.amazonaws.com/rsconnect
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: acl
          dir: |
            .:/chris_app/